---
title: "Analisis de ocurrencias GBIF - Scaptotrigona"
author: "Brahyan_Muñoz"
date: "2026-01-27"
output: html_document
---
## R Markdown
Las abejas del género Scaptotrigona son abejas sin aguijón que se distribuyen en el neotrópico. Vamos a análizar los datos descargados de la plataforma GBIFF y guardados en la carpeta de la sesión de hoy 
```{r scapto}
# definimos como directorio de trabajo la carpeta creada
setwd("C:/Users/brahy/Biologia_Computacional/Clase_2")
# leemos los datos descargados y guardados
gbif_data <- read.csv(
  "Gbiff_Scrapto_Colombia.csv",
  row.names = NULL, #necesario para que no numere las filas 
  stringsAsFactors = FALSE, 
  sep = "\t" #la separación de columnas es tipo "tab"
)

#gbif_data <- read_csv("Gbiff_Scrapto_Colombia.csv")

#Cuantas especies hay?
tabla_sp <- table(gbif_data$species)

```

## Incluir Gráficos

Cuantas especies de este género se reportan en la base de datos?  

```{r barplot, echo=FALSE}
# Ajustar márgenes (más espacio abajo para los nombres)
par(mar = c(10, 5, 4, 2))


barplot(
tabla_sp,
las = 2, # etiquetas verticales
col = "green", # color verde
border = "green", # borde verde más oscuro
main = "Ocurrencias de Scaptotrigona por especie (GBIF)",
ylab = "Número de registros",
cex.names = 0.9, # tamaño de nombres en eje X
cex.axis = 0.9, # tamaño de números
cex.lab = 1.1, # tamaño etiquetas de ejes
cex.main = 1.2 # tamaño del título
)

```
#Edicion para chequear github local
